#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "This is a Linux system, nice."
    sudo apt update
    sudo apt install vim tmux zsh htop curl git nodejs npm -y
    sudo snap install spotifyd -y
    sudo snap install spotify -y
    sudo snap install discord -y
    sudo snap install slack --classic -y
    sudo snap install code --classic -y
    # cava
    sudo add-apt-repository ppa:hsheth2/ppa -y
    sudo apt update
    sudo apt install cava -y
    # tlp
    sudo add-apt-repository ppa:linrunner/tlp -y
    sudo apt update
    sudo apt install tlp tlp-rdw -y
    sudo apt install acpi-call-dkms tp-smapi-dkms -y
    sudo tlp start
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Dealing with OSX crap"
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing homebrew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    if [ -f "$HOME/.Brewfile" ]; then
        echo "Updating homebrew bundle"
        brew bundle --global
    fi
fi

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin git@github.com:yuntsewu/.dotfiles.git 

git config --global user.email "windsor106@gmail.com"
git config --global user.name "Yun Tse Wu"
